project:
  type: website

website:
  title: "tutorials"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Reader.qmd
        text: Reader
      - href: wikidata-tutorial.qmd
        text: Wikidata

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

