project:
  type: website

website:
  title: "Readers & Tutorials"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Reader.qmd
        text: Reader
      - href: personal-tools.qmd
        text: Personal Tools
      - href: wikidata-tutorial.qmd
        text: Wikidata
    tools:
      - icon: linkedin
        menu:
           - text: Daniel Antal
             url: https://www.linkedin.com/in/antaldaniel/
           - text: Reprex
             url: https://www.linkedin.com/company/68855596/
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/dataobservatory-eu/opencollections-tutorials
          - text: Report an Error
            url:  https://github.com/dataobservatory-eu/opencollections-tutorials/issues
          - text: Request Improvements
            url:  https://github.com/dataobservatory-eu/opencollections-tutorials/issues

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

